### ISSUE TITLE
why are the statically linked libraries not part of the nuget package?

### ISSUE THREAD

**Issue by janwilmans** [sergey-shandar/getboost#29]

**Comment by sergey-shandar** [comment]
Because if I add all statically linked libraries, the NuGet package will be huge. About 50 GB, I think.

**Comment by janwilmans** [comment]
Its more like 5 GB, but I see you point. I would still prefer it over having all developers on my projects build boost themselves, would it be an option to put it in a separate nuget?

**Comment by sergey-shandar** [comment]
@janwilmans it's already there. You can see links on NuGet packages for different version of Visual Studio on the front page https://github.com/sergey-shandar/getboost.

Also, there are a page with all NuGet packages produced by this project for a specific version of Boost

https://github.com/sergey-shandar/getboost/blob/master/releases/1.63.md

**Comment by janwilmans** [comment]
wait, first you say, it would get large if you add the static libraries, and then you say its already there, I'm confused, do you mean there is already a boost 1.63 nuget package _with_ static libraries? if so which one is it?

**Comment by sergey-shandar** [comment]
That's correct. The NuGet package becames too large. So I will not change **the main "boost"** NuGet package because there are a lot of customers who would like to have headers-only libraries. In the same time, getboost produces NuGet packages which contains precompiled lib/dll files for specific libraries. So, the workflow should be like this:

1. Install Boost NuGet package.
2. If linker complains about specific libraries, install additional Boost NuGet packages for these libraries.

If you don't have time and don't care about disk space and download time, then you may use NuGet packages which **reference** all NuGet packages with precompiled files. It's still for a specific compiler.

**Comment by sergey-shandar** [comment]
https://github.com/sergey-shandar/getboost/blob/master/releases/1.63.md#libraries

- all libraries [vc100](http://nuget.org/packages/boost-vc100/1.63.0.0) [vc110](http://nuget.org/packages/boost-vc110/1.63.0.0) [vc120](http://nuget.org/packages/boost-vc120/1.63.0.0) [vc140](http://nuget.org/packages/boost-vc140/1.63.0.0) [vc80](http://nuget.org/packages/boost-vc80/1.63.0.0) [vc90](http://nuget.org/packages/boost-vc90/1.63.0.0)

**Comment by janwilmans** [comment]
that is great! nice work!
