### ISSUE TITLE
The member std::fpos::seekpos() is non-Standard

### ISSUE THREAD

**Issue by elyasnew** [sergey-shandar/getboost#44]
When I want to debug and build my project it gives me this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'std::fpos<_Mbstatet>::seekpos': warning STL4019: The member std::fpos::seekpos() is non-Standard, and is preserved only for compatibility with workarounds for old versions of Visual C++. It will be removed in a future release, and in this release always returns 0. Please use standards-conforming mechanisms to manipulate fpos, such as conversions to and from streamoff, or an integral type, instead. If you are receiving this message while compiling Boost.IOStreams, a fix has been submitted upstream to make Boost use standards-conforming mechanisms, as it does for other compilers. You can define _SILENCE_FPOS_SEEKPOS_DEPRECATION_WARNING to acknowledge that you have received this warning, or define _REMOVE_FPOS_SEEKPOS to remove std::fpos::seekpos entirely.

**Comment by code-affinity** [comment]
I am not involved with fixing this issue, but I have been keeping track of it because it is a big problem for me.  Here's what I know: The pull request that fixes this problem is https://github.com/boostorg/iostreams/pull/57.  My understanding is that it has been incorporated into Boost 1.69.  https://github.com/boostorg/iostreams/pull/57#issuecomment-430205532

**Comment by chcg** [comment]
@sergey-shandar https://www.boost.org/users/history/version_1_69_0.html is available. Are you planning a release?

**Comment by sergey-shandar** [comment]
@chcg yes, I plan to release 1.69 this week.
